"""initial schema

Revision ID: 3451f586b06c
Revises: 
Create Date: 2026-03-28 23:38:58.189058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3451f586b06c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('entities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('thesis_key', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('novelty_hash', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload_ref', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('source_ref', name=op.f('uq_events_source_ref'))
    )
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index('ix_events_novelty', 'events', ['novelty_hash'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_index('ix_events_source_occurred', 'events', ['source', 'occurred_at'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('magnitude_expected', sa.Float(), nullable=True),
    sa.Column('timeframe_hours', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('implication_id', sa.String(length=36), nullable=True),
    sa.Column('signal_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_direction', sa.String(length=16), nullable=True),
    sa.Column('outcome_magnitude', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.Column('grade_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecasts'))
    )
    op.create_index(op.f('ix_forecasts_created_at'), 'forecasts', ['created_at'], unique=False)
    op.create_table('implications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headline', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('implications', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('signal_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('event_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('world_model_updates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=16), nullable=True),
    sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_implications'))
    )
    op.create_index(op.f('ix_implications_created_at'), 'implications', ['created_at'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('entities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('thesis_key', sa.String(length=128), nullable=True),
    sa.Column('evidence_strength', sa.Float(), nullable=False),
    sa.Column('novelty', sa.Float(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('timeliness', sa.Float(), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('score_raw', sa.Float(), nullable=False),
    sa.Column('score_calibrated', sa.Float(), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_event_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index(op.f('ix_signals_detected_at'), 'signals', ['detected_at'], unique=False)
    op.create_index('ix_signals_score', 'signals', ['score_calibrated'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index('ix_signals_urgency_detected', 'signals', ['urgency', 'detected_at'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('handle', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('themes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('sectors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('useful_events', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('handle', name=op.f('uq_sources_handle'))
    )
    op.create_table('world_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_regime', sa.Float(), nullable=False),
    sa.Column('risk_regime_label', sa.String(length=32), nullable=False),
    sa.Column('risk_regime_reason', sa.Text(), nullable=False),
    sa.Column('vix_regime', sa.Float(), nullable=False),
    sa.Column('vix_regime_label', sa.String(length=32), nullable=False),
    sa.Column('vix_regime_reason', sa.Text(), nullable=False),
    sa.Column('geo_risk', sa.Float(), nullable=False),
    sa.Column('geo_risk_label', sa.String(length=32), nullable=False),
    sa.Column('geo_risk_reason', sa.Text(), nullable=False),
    sa.Column('fed_stance', sa.Float(), nullable=False),
    sa.Column('fed_stance_label', sa.String(length=32), nullable=False),
    sa.Column('fed_stance_reason', sa.Text(), nullable=False),
    sa.Column('smart_money_flow', sa.Float(), nullable=False),
    sa.Column('smart_money_flow_label', sa.String(length=32), nullable=False),
    sa.Column('smart_money_flow_reason', sa.Text(), nullable=False),
    sa.Column('sector_leader', sa.String(length=64), nullable=False),
    sa.Column('sector_leader_reason', sa.Text(), nullable=False),
    sa.Column('next_catalyst', sa.String(length=256), nullable=False),
    sa.Column('next_catalyst_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_state'))
    )
    op.create_table('world_state_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('variable', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.Float(), nullable=False),
    sa.Column('new_value', sa.Float(), nullable=False),
    sa.Column('old_label', sa.String(length=32), nullable=False),
    sa.Column('new_label', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('trigger_signal_id', sa.String(length=36), nullable=True),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world_state_log'))
    )
    op.create_index(op.f('ix_world_state_log_created_at'), 'world_state_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_world_state_log_variable'), 'world_state_log', ['variable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_state_log_variable'), table_name='world_state_log')
    op.drop_index(op.f('ix_world_state_log_created_at'), table_name='world_state_log')
    op.drop_table('world_state_log')
    op.drop_table('world_state')
    op.drop_table('sources')
    op.drop_index('ix_signals_urgency_detected', table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index('ix_signals_score', table_name='signals')
    op.drop_index(op.f('ix_signals_detected_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_implications_created_at'), table_name='implications')
    op.drop_table('implications')
    op.drop_index(op.f('ix_forecasts_created_at'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('ix_events_source_occurred', table_name='events')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index('ix_events_novelty', table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
