"""add_signal_fingerprint_column

Revision ID: b09f2416852d
Revises: 3451f586b06c
Create Date: 2026-03-29 14:47:59.564062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09f2416852d'
down_revision: Union[str, Sequence[str], None] = '3451f586b06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first, backfill existing rows, then set NOT NULL
    op.add_column('signals', sa.Column('fingerprint', sa.String(length=20), nullable=True, server_default=''))
    op.execute("UPDATE signals SET fingerprint = '' WHERE fingerprint IS NULL")
    op.alter_column('signals', 'fingerprint', nullable=False)
    op.create_index(op.f('ix_signals_fingerprint'), 'signals', ['fingerprint'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_fingerprint'), table_name='signals')
    op.drop_column('signals', 'fingerprint')
    # ### end Alembic commands ###
